module.exports.ingredients = [
    ['butter', true],
    ['salt', false],
    ['water', true],
    ['yeast', false],
    ['olive oil', false],
    ['chicken', true],
    ['all purpose flour', false],
    ['sugar', false],
    ['egg', true],
    ['rice', false],
    ['vegetable oil', false],
    ['pork', true],
    ['beef', true],
    ['cheese', false],
    ['garlic', false],
    ['orange', false],
    ['turkey', true],
    ['onion', false],
    ['corn', false],
    ['whole milk', true],
    ['mayonnaise', false],
    ['chiles', false],
    ['almonds', false],
    ['mushrooms', false], // 24
    ['bacon', true],
    ['coconut', false],
    ['beets', false],
    ['strawberries', false],
    ['fennel', false],
    ['lamb', true],
    ['apple', false],
    ['shrimp', false],
    ['lobster', true],
    ['olive oil', false],
    ['splenda', false],
    ['honey', false],
    ['molasses', false],
    ['white vinegar', false],
    ['balsamic vinegar', false],
    ['baking soda', false],
    ['baking powder', false],
    ['cocoa powder', false],
    ['peanut oil', false],
    ['spray oil', true],
    ['sea salt', false],
    ['basil', false],
    ['oregano', false],
    ['parsley', false],
    ['garlic powder', false],
    ['onion powder', false],
    ['cinnamon', false],
    ['nutmeg', false],
    ['chili', false],
    ['vanilla extract', false],
    ['rum', false],
    ['almond flour', false],
    ['coconut flour', false],
    ['flax seed meal', false],
    ['chia seeds', false],
    ['soy sauce', false],
    ['black olives', false],
    ['organic chicken broth', false],
    ['chicken broth', true],
    ['feta', true],
    ['cheddar', true],
    ['parmesan', true],
    ['mozzarella', true],
    ['yogurt', true],
    ['cottage cheese', true],
    ['whipping cream', true],
    ['chicken breast', true],
    ['pepperoni', true],
    ['salami', true],
    ['hot dogs', true],
    ['green breans', false],
    ['tomatoes', false],
    ['pickles', false],
    ['cucumber', false],
    ['zucchini', false],
    ['cauliflower', false],
    ['spinach', false],
    ['lettuce', false],
    ['lemon juice', false],
    ['olives', false],
    ['almond milk', false],
    ['coconut milk', false],
    ['carrots', false],
    ['ginger root', false],
    ['red bell pepper', false],
    ['barbecue sauce', false],
    ['coleslaw', false],
    ['grass-fed beef', true],
    ['tomato sauce', false],
    ['pasture-raised mozzarella', false],
    ['vegan mozzarella', false],
    ['pasture-raised butter', false],
    ['free-range chicken', false],
    ['pasture-raised egg', false],
    ['pasture-raised pork', false],
    ['pasture-raised beef', false],
    ['pasture-raised turkey', false],
    ['organic milk', false],
    ['organic bacon', false],
    ['pasture-raised lamb', false],
    ['oil and a brush', false],
    ['organic chicken broth', false],
    ['organic feta', false],
    ['organic cheddar', false],
    ['organic parmesan', false],
    ['organic mozzarella', false],
    ['organic yogurt', false],
    ['organic cottage cheese', false],
    ['organic whipping cream', false],
    ['organic chicken breast', false],
    ['organic pepperoni', false],
    ['organic salami', false],
    ['organic hot dogs', false],
    ['egg noodle', true],
    ['organic egg noodle', false],
    ['seitan', false], // 120
    ['tofu', false], // 121
    ['tempeh', false], // 122
    ['jackfruit', false], // 123
    ['cauliflower', false], // 124
    ['eggplant', false], //125,
    ['soymilk', false], // 126
    ['rice milk', false],// 127
    ['mushroom broth', false], // 128
    ['vegetable broth', false], // 129
    ['basil pesto', false], // 130
    ['organic sour cream', false], //131
    ['buns', false], // 132
    ['linguine', false]
];   