export const tasks = [{ id: 1, text: "ground cinnamon" },
  { id: 2, text: "salt" },
  { id: 3, text: "sugar" },
  { id: 4, text: "butter"},
  { id: 5, text: "black pepper" },
  { id: 6, text: "onion" },
  { id: 7, text: "eggs" },
  { id: 8, text: "all-purpose flour" },
  { id: 9, text: "water" },
  { id: 10, text: "olive oil" },
  { id: 11, text: "pepper"},
  { id: 12, text: "milk" },
  { id: 13, text: "garlic cloves" },
  { id: 14, text: "unsalted butter" },
  { id: 15, text: "vegetable oil" },
  { id: 16, text: "extra-virgin olive oil" },
  { id: 17, text: "brown sugar" },
  { id: 18, text: "baking powder" },
  { id: 19, text: "lemon juice" },
  { id: 20, text: "vanilla extract" },
  { id: 21, text: "freshly ground pepper" },
  { id: 22, text: "carrots" },
  { id: 23, text: "cloves garlic" },
  { id: 24, text: "flour" },
  { id: 25, text: "baking soda" },
  { id: 26, text: "tomatoes" },
  { id: 27, text: "kosher salt" },
  { id: 28, text: "green onions" },
  { id: 29, text: "large eggs" },
  { id: 30, text: "sour cream" },
  { id: 31, text: "honey" },
  { id: 32, text: "cream cheese" },
  { id: 33, text: "granulated sugar" },
  { id: 34, text: "red onion" },
  { id: 35, text: "chicken broth" },
  { id: 36, text: "fresh parsley" },
  { id: 37, text: "garlic powder" },
  { id: 38, text: "cornstarch" },
  { id: 39, text: "oil" },
  { id: 40, text: "grated parmesan cheese" },
  { id: 41, text: "minced garlic" },
  { id: 42, text: "white sugar" },
  { id: 43, text: "mayonnaise" },
  { id: 44, text: "ground cumin" },
  { id: 45, text: "soy sauce" },
  { id: 46, text: "fresh lemon juice" },
  { id: 47, text: "heavy cream" },
  { id: 48, text: "cinnamon" },
  { id: 49, text: "margarine" },
  { id: 50, text: "celery" }];
